# Generated by Django 3.0.6 on 2020-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reciepe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='ingredients',
            field=models.ManyToManyField(to='core.Ingredient'),
        ),
        migrations.AddField(
            model_name='reciepe',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
