# Generated by Django 3.0.6 on 2020-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200617_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='time_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
