# Generated by Django 3.0.6 on 2020-06-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reciepe_time_minutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciepe',
            new_name='Recipe',
        ),
    ]
